version: '3.8'
services:
  postgres:
    image: postgres
    container_name: nrs-postgres-container
    environment:
      POSTGRES_PASSWORD: nrs
      POSTGRES_USER: nrspostgres
      POSTGRES_DB: nrspostgres
    ports:
      - "5432:5432"
  express-app:
    image: nrs-backend/dockerize-express-app:latest
    container_name: nrs-backend-app-container
    environment:
      DB_USER: nrspostgres
      DB_HOST: postgres
      DB_DATABASE: nrspostgres
      DB_PASSWORD: nrs
      DB_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - postgres
